import { RadarConfig } from "./radar-types";

// Technology Radar
// Auto-generated radar data for technology radar
export const technologyRadar: RadarConfig = {
  id: "technology",
  title: "Technology Radar",
  quadrants: [
    {
      name: "Techniques",
      color: "#8FA1B3",
    },
    {
      name: "Tools",
      color: "#B48EAD",
    },
    {
      name: "Platforms",
      color: "#A3BE8C",
    },
    {
      name: "Languages & Frameworks",
      color: "#CD853F",
    },
  ],
  rings: ["Adopt", "Trial", "Assess", "Hold"],
  entries: [
    {
      id: "typescript",
      name: "TypeScript",
      quadrant: 3,
      ring: 0,
      description:
        "Typed superset of JavaScript that compiles to plain JavaScript. Dramatically improves code quality, maintainability, and developer experience. De facto standard for modern JavaScript development.",
      tags: ["javascript", "type-safety", "frontend", "backend"],
      url: "https://www.typescriptlang.org/",
      moved: 0,
      last_update: "2025-01-15",
    },
    {
      id: "kubernetes",
      name: "Kubernetes",
      quadrant: 2,
      ring: 1,
      description:
        "Production-grade container orchestration platform. Powerful but complex. Consider for large-scale deployments with multiple services.",
      tags: ["containers", "orchestration", "cloud-native"],
      url: "https://kubernetes.io/",
      moved: 1,
      last_update: "2025-01-15",
    },
    {
      id: "ci-cd-automation",
      name: "CI/CD Automation",
      quadrant: 0,
      ring: 0,
      description:
        "Automated testing, building, and deployment pipelines. Critical for modern software development. Reduces human error and accelerates delivery.",
      tags: ["automation", "devops", "testing"],
      moved: 0,
      last_update: "2025-01-15",
    },
    {
      id: "micro-frontends",
      name: "Micro Frontends",
      quadrant: 0,
      ring: 2,
      description:
        "Architectural approach to split frontend monoliths into smaller, more manageable pieces. Promising but adds complexity. Assess carefully before adopting.",
      tags: ["architecture", "frontend", "modularity"],
      moved: 0,
      last_update: "2025-01-15",
    },
    {
      id: "openshift",
      name: "Openshift Container Platform",
      quadrant: 2,
      ring: 0,
      description:
        "Red Hat® OpenShift® Container Platform is a consistent hybrid cloud foundation for building and scaling containerized applications. Red Hat OpenShift is trusted by thousands of customers in every industry to deliver business-critical applications, whether they're migrating existing workloads to the cloud or building new experiences for customers. It's also backed by one of the leading Kubernetes contributors, Red Hat.",
      tags: ["containers", "devops", "infrastructure"],
      url: "https://www.redhat.com/en/technologies/cloud-computing/openshift/container-platform",
      image: "",
      moved: 0,
      last_update: "2025-07-11",
    },
    {
      id: "arc-browser",
      name: "Arc Browser",
      quadrant: 1,
      ring: 1,
      description:
        'Arc is a web browser developed by The Browser Company that is designed to be a more integrated and efficient tool for managing internet activity, featuring a unique left-side sidebar for tabs and spaces, and an AI assistant called "Max". It is Chromium-based, making it compatible with Google Chrome extensions. While initially focused on macOS, Arc is now available for Windows and mobile devices.',
      tags: ["productivity", "browser", "ai", "minimalist"],
      url: "https://arc.net/",
      image: "",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "akiflow",
      name: "Akiflow",
      quadrant: 1,
      ring: 1,
      description:
        "Akiflow is a productivity app and digital planner that consolidates tasks from various other apps into a single inbox and calendar view, allowing users to manage their workload with time blocking. It integrates with many popular tools like Slack, Gmail, Notion, and Asana, and provides features for capturing tasks, scheduling them into time slots, and tracking productivity. Akiflow is designed for individuals who need to organize and manage their personal productivity across multiple platforms.",
      tags: ["productivity", "planner", "calendar", "integration"],
      url: "https://akiflow.com/",
      image: "/radar/03-akiflow.png",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "rust",
      name: "Rust",
      quadrant: 3,
      ring: 0,
      description:
        "Rust is a multi-paradigm, compiled programming language known for its focus on performance, memory safety, and concurrency. It is often described as a modern alternative to C and C++ for systems programming, offering similar low-level control but with stronger guarantees about memory safety without requiring a garbage collector.",
      tags: ["coding", "performance", "memory-safety", "backend"],
      url: "",
      image: "",
      moved: 1,
      last_update: "2025-07-11",
    },
    {
      id: "kotlin",
      name: "Kotlin",
      quadrant: 3,
      ring: 0,
      description:
        "Kotlin is a modern, statically typed, general-purpose programming language developed by JetBrains. It is designed to be fully interoperable with Java and the Java Virtual Machine (JVM), making it a popular choice for Android development, where it is the preferred language.",
      tags: ["coding", "android", "coroutines"],
      url: "https://kotlinlang.org/",
      image: "/radar/02-kotlin.png",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "python",
      name: "Python",
      quadrant: 3,
      ring: 0,
      description:
        "Python is a high-level, interpreted, general-purpose programming language. Created by Guido van Rossum and first released in 1991, it is known for its emphasis on code readability and its use of significant indentation.",
      tags: ["coding", "ai", "data-science", "automation", "scripting", "lightweight"],
      url: "https://www.python.org/",
      image: "",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "keycloak",
      name: "Keycloak",
      quadrant: 2,
      ring: 0,
      description:
        "Keycloak is an open-source identity and access management (IAM) solution that secures applications and services with a central login, enabling single sign-on (SSO). It handles user authentication, authorization, and user management, providing a unified user experience and strong security by supporting standard protocols like OpenID Connect, OAuth 2.0, and SAML. This makes it flexible for both modern applications, like single-page applications and mobile apps, and traditional enterprise environments.",
      tags: ["authorization", "authentication", "oidc", "saml", "open-source", "iam"],
      url: "https://www.keycloak.org/",
      image: "",
      moved: 0,
      last_update: "2025-07-11",
    },
    {
      id: "apache-spark",
      name: "Apache Spark",
      quadrant: 1,
      ring: 1,
      description:
        "Apache Spark is an open-source, unified analytics engine designed for large-scale data processing. It uses in-memory processing for speed, making it significantly faster than disk-based systems. Spark provides APIs for various languages like Python, Java, and Scala, and is used for a wide range of tasks, including batch processing, real-time streaming, machine learning, and graph processing.",
      tags: ["data-science", "machine-learning", "coding"],
      url: "https://spark.apache.org/",
      image: "",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "redhat-service-mesh",
      name: "Red Hat Service Mesh",
      quadrant: 2,
      ring: 1,
      description:
        "Red Hat® OpenShift® Service Mesh offers a uniform way to connect, manage, observe, and provide security for microservices-based applications. It includes behavioral insight into—and control of—the networked microservices in your service mesh. OpenShift Service Mesh is based on the open source Istio, Envoy, and Kiali projects. It supports the Istioctl command line utility for diagnostics and management of the control plane and data plane, along with the Kiali and OpenShift Service Mesh Console dashboards.",
      tags: ["microservices", "containers", "network", "istio"],
      url: "https://www.redhat.com/en/technologies/cloud-computing/openshift/what-is-openshift-service-mesh",
      image: "",
      moved: 0,
      last_update: "2025-07-11",
    },
    {
      id: "jaeger",
      name: "Jaeger",
      quadrant: 1,
      ring: 1,
      description:
        "Jaeger is an open-source distributed tracing system used to monitor and troubleshoot complex microservice-based applications. It visualizes the path of a single request as it travels across multiple services, which helps developers identify performance bottlenecks and pinpoint the root cause of errors. Key functions include distributed context propagation, performance monitoring, and service dependency analysis.",
      tags: ["monitoring", "tracing", "microservices", "open-source"],
      url: "https://www.jaegertracing.io/",
      image: "",
      moved: 0,
      last_update: "2025-11-07",
    },
    {
      id: "mdx",
      name: "MDX",
      quadrant: 3,
      ring: 1,
      description:
        "An MDX file is a file format that combines Markdown with JSX, allowing you to write standard Markdown text and also embed and use interactive components like those from React directly within the same file. To use one, you can create it by simply renaming a .md file to .mdx in a framework that supports it, like Next.js or Gatsby. You can then import and use JSX components within the Markdown structure, and the file will be compiled into a JavaScript/React component that can be rendered by the application.",
      tags: ["jsx", "react", "templating", "docs"],
      url: "https://mdxjs.com/",
      image: "/radar/04-mdx.png",
      moved: 1,
      last_update: "2025-11-07",
    },
    {
      id: "ansible",
      name: "Ansible",
      quadrant: 1,
      ring: 1,
      description:
        "Ansible is an open-source IT automation tool that simplifies complex tasks like provisioning, configuration management, and application deployment across servers and other infrastructure. It uses an agentless architecture, which means it doesn't require any special software on the nodes it manages, and it connects to target machines via SSH to send small modules that perform specific tasks. This allows IT professionals to automate repetitive tasks and maintain consistent, reliable environments, saving time and reducing manual errors",
      tags: ["automation", "config-management", "orchestration", "open-source"],
      url: "https://docs.ansible.com/ansible/latest/getting_started/introduction.html",
      image: "/radar/05-ansible.png",
      moved: 0,
      last_update: "2025-11-07",
    },
  ],
};
